### PR TITLE
WIP: advanced scan scheduling API

### PR DESCRIPTION
**Pull request by KingBrewer**
Advanced Scan Scheduling API - OpenAPI

Caution: **work in-progress**

### CODE REVIEW

**Comment by KingBrewer** [comment]
@ptrakhtman FYI. Work is in-progress though so `do-not-merge` yet please.

**Comment by anton-b** [comment]
@KingBrewer ready to merge?

**Comment by KingBrewer** [comment]
work-in-progress, do-not-merge :) will notify you once we've finished

**Comment by anton-b** [comment]
please move definitions to your service's repo:
`/doc/openapi/<service_name>.v<api_version>.yaml`

https://algithub.pd.alertlogic.net/alertlogic/route105-docs/pull/464/files#diff-66fda837e311b9acb0ab47d2c0b38175R32

**Comment by msayler** [comment]
merged elsewhere as noted.

**Pull request closed without merging**
